In [1]:
import pandas as pd
df = pd.read_csv("cyber security data.csv")
df.head(10)

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign
5,2025-10-01 00:56:45,38.222.6.74,191.130.7.118,58858,445,UDP,150393,94993,curl/8.4.0,NaN,False,0,benign
6,2025-10-01 01:19:57,238.229.195.174,16.182.72.24,25167,443,TCP,3592,1081,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,https://internal.bank.local/?id=432022,True,0,benign
7,2025-10-01 01:34:30,81.21.49.235,119.87.191.7,37602,22,TCP,123317,41293,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=957608,False,0,benign
8,2025-10-01 01:35:33,137.181.221.157,44.124.13.254,18315,53,TCP,97222,233071,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,https://internal.bank.local/admin?id=567716,False,0,benign
9,2025-10-01 01:40:38,236.139.171.70,89.15.217.112,12283,21,TCP,17289,35727,Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like M...,NaN,False,0,benign

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            10000 non-null  object
 1   src_ip               10000 non-null  object
 2   dst_ip               10000 non-null  object
 3   src_port             10000 non-null  int64
 4   dst_port             10000 non-null  int64
 5   protocol             10000 non-null  object
 6   bytes_sent           10000 non-null  int64
 7   bytes_received       10000 non-null  int64
 8   user_agent           10000 non-null  object
 9   url                  6768 non-null   object
 10  is_internal_traffic  10000 non-null  bool
 11  label                10000 non-null  int64
 12  attack_type          10000 non-null  object
dtypes: bool(1), int64(5), object(7)
memory usage: 947.4+ KB

In [3]:
df.isnull().sum()

timestamp                 0
src_ip                    0
dst_ip                    0
src_port                  0
dst_port                  0
protocol                  0
bytes_sent                0
bytes_received            0
user_agent                0
url                    3232
is_internal_traffic       0
label                     0
attack_type               0
dtype: int64

In [4]:
df.nunique().sort_values()

is_internal_traffic        2
label                      2
protocol                   3
attack_type               10
user_agent                13
dst_port                 449
url                     6768
src_port                7647
bytes_sent              9280
bytes_received          9541
timestamp               9998
src_ip                 10000
dst_ip                 10000
dtype: int64

In [5]:
df.head()

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,bytes_sent,bytes_received,user_agent,url,is_internal_traffic,label,attack_type
0,2025-10-01 00:12:54,188.176.27.165,253.240.113.218,56377,445,TCP,8029,17204,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/login?id=385071,False,0,benign
1,2025-10-01 00:23:43,68.59.26.43,212.75.38.111,51165,1433,TCP,676368,2643374,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/owa/auth/logon.aspx...,False,0,benign
2,2025-10-01 00:25:46,119.204.243.78,90.28.90.234,14948,1433,TCP,316502,38571,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,False,0,benign
3,2025-10-01 00:27:21,122.119.194.175,175.140.78.230,36097,443,TCP,70933,21935,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://webmail.corp/phpmyadmin?id=114701,False,0,benign
4,2025-10-01 00:40:09,181.199.242.68,55.99.177.69,445,21255,TCP,12721,9939,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,https://portal.example.org/config.php?id=345569,False,0,benign

In [6]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

timestamp: 9998 unique values
src_ip: 10000 unique values
dst_ip: 10000 unique values
src_port: 7647 unique values
dst_port: 449 unique values
protocol: 3 unique values
bytes_sent: 9280 unique values
bytes_received: 9541 unique values
user_agent: 13 unique values
url: 6768 unique values
is_internal_traffic: 2 unique values
label: 2 unique values
attack_type: 10 unique values

In [7]:
df["url_missing"] = df["url"].isna()
print(df.groupby("url_missing")["label"].value_counts(normalize=True) * 100)

url_missing  label
False        0        96.025414
             1         3.974586
True         0        95.946782
             1         4.053218
Name: proportion, dtype: float64

In [8]:
pd.crosstab(df["url_missing"], df["attack_type"])

attack_type,benign,brute-force,c2,command-injection,credential-stuffing,ddos,exploit-attempt,port-scan,sql-injection,xss
url_missing,,,,,,,,,,
False,6499,75,7,17,17,19,17,50,43,24
True,3101,33,3,9,11,8,5,31,21,10

In [9]:
pd.crosstab(df["url_missing"],df["protocol"],normalize="index") * 100

protocol         ICMP        TCP        UDP
url_missing
False        2.984634  78.339243  18.676123
True         3.805693  76.206683  19.987624

In [10]:
pd.crosstab(df["url_missing"],df["is_internal_traffic"],normalize="index") * 100

is_internal_traffic      False      True
url_missing
False                85.150709  14.849291
True                 83.632426  16.367574

In [11]:
url_port_analysis = (df.groupby("dst_port")["url_missing"].agg(["count", "sum", "mean"])
      .sort_values("mean", ascending=False))
url_port_analysis.head(15)

          count  sum  mean
dst_port
10755         1    1   1.0
19040         1    1   1.0
12946         1    1   1.0
13075         1    1   1.0
13328         1    1   1.0
13522         1    1   1.0
13589         1    1   1.0
14257         1    1   1.0
14372         1    1   1.0
44991         1    1   1.0
44662         1    1   1.0
44619         1    1   1.0
15405         1    1   1.0
15510         1    1   1.0
15732         1    1   1.0

In [12]:
url_src_port_analysis = (df.groupby("src_port")["url_missing"].agg(["count", "sum", "mean"])
      .sort_values("mean", ascending=False))
url_src_port_analysis.head(15)

          count  sum  mean
src_port
19990         1    1   1.0
50168         1    1   1.0
50418         1    1   1.0
22440         1    1   1.0
50403         1    1   1.0
50379         1    1   1.0
22482         1    1   1.0
22527         1    1   1.0
50366         1    1   1.0
22538         1    1   1.0
22570         1    1   1.0
22576         1    1   1.0
22581         1    1   1.0
22596         1    1   1.0
50280         1    1   1.0

In [13]:
pd.crosstab(df["url_missing"],df["user_agent"])

user_agent,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0,Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html),Mozilla/5.0 (compatible; sqlmap/1.7),"Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1",curl/7.81.0,curl/8.4.0,python-requests/2.28,python-requests/2.31.0,python-urllib/3.9,sqlmap/1.8,zgrab/0.x
url_missing,,,,,,,,,,,,,
False,1682,2315,285,316,18,805,13,556,15,389,214,84,76
True,803,1143,107,150,9,400,8,250,8,192,90,34,38

In [14]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [15]:
url_time = (df.groupby(df["timestamp"].dt.date)["url_missing"].agg(["count", "sum", "mean"]))
url_time.head()

            count  sum      mean
timestamp
2025-10-01    104   40  0.384615
2025-10-02     92   32  0.347826
2025-10-03     85   31  0.364706
2025-10-04    111   43  0.387387
2025-10-05    112   41  0.366071

In [16]:
url_time["mean"].describe()

count    90.000000
mean      0.323314
std       0.051024
min       0.201754
25%       0.283880
50%       0.324067
75%       0.359186
max       0.445378
Name: mean, dtype: float64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            10000 non-null  datetime64[ns]
 1   src_ip               10000 non-null  object
 2   dst_ip               10000 non-null  object
 3   src_port             10000 non-null  int64
 4   dst_port             10000 non-null  int64
 5   protocol             10000 non-null  object
 6   bytes_sent           10000 non-null  int64
 7   bytes_received       10000 non-null  int64
 8   user_agent           10000 non-null  object
 9   url                  6768 non-null   object
 10  is_internal_traffic  10000 non-null  bool
 11  label                10000 non-null  int64
 12  attack_type          10000 non-null  object
 13  url_missing          10000 non-null  bool
dtypes: bool(2), datetime64[ns](1), int64(5), object(6)
memory usage: 957.2+ KB

In [18]:
df["url_missing"]

0       False
1       False
2        True
3       False
4       False
        ...
9995     True
9996    False
9997     True
9998    False
9999    False
Name: url_missing, Length: 10000, dtype: bool

In [19]:
df.drop("url_missing", axis=1, inplace=True)

In [20]:
df.columns

Index(['timestamp', 'src_ip', 'dst_ip', 'src_port', 'dst_port', 'protocol',
       'bytes_sent', 'bytes_received', 'user_agent', 'url',
       'is_internal_traffic', 'label', 'attack_type'],
      dtype='object')